//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoipApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendsList
    {
        public int UserId { get; set; }
        public int FriendId { get; set; }
        public string FriendName { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
